# Generated by Django 5.1.3 on 2025-03-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='active_type',
            field=models.CharField(blank=True, choices=[('item', 'item'), ('point_item', 'point_item'), ('package', 'package')], max_length=13, null=True),
        ),
    ]
