# Generated by Django 5.1.3 on 2025-03-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_order_active_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_points_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price_items',
            field=models.IntegerField(default=0),
        ),
    ]
