# Generated by Django 5.1.3 on 2025-02-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('student', 'Student'), ('doctor', 'Doctor')], default='111', max_length=10),
        ),
    ]
