# Generated by Django 5.1.3 on 2025-02-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('student', 'Student'), ('doctor', 'Doctor')], max_length=10),
        ),
    ]
