# Generated by Django 5.1.3 on 2025-03-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_order_total_points_items_order_total_price_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchased_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
