# Generated by Django 5.1.3 on 2025-03-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_order_purchased_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='purchased_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
