# Generated by Django 5.1.3 on 2025-02-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_package_packageitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageitem',
            name='price',
        ),
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
