# Generated by Django 5.1.3 on 2025-05-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_order_purchased_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_type',
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('student', 'Student'), ('doctor', 'Doctor')], default=132, max_length=10),
            preserve_default=False,
        ),
    ]
