# Generated by Django 5.1.3 on 2025-02-28 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_remove_packageitem_price_package_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='photo',
        ),
    ]
