# Generated by Django 5.1.3 on 2025-05-15 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_remove_item_item_type_category_category_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_points_items',
            new_name='total_points',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_price_items',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='active_type',
            field=models.CharField(blank=True, choices=[('price', 'price'), ('point', 'point')], max_length=13, null=True),
        ),
        migrations.RemoveField(
            model_name='order',
            name='package',
        ),
        migrations.CreateModel(
            name='OrderPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.order')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.package')),
            ],
        ),
        migrations.DeleteModel(
            name='PackageItem',
        ),
        migrations.AddField(
            model_name='order',
            name='package',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', through='item.OrderPackage', to='item.package'),
        ),
    ]
