# Generated by Django 5.1.3 on 2025-05-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_rename_total_points_items_order_total_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='package',
            field=models.ManyToManyField(blank=True, related_name='orders', through='item.OrderPackage', to='item.package'),
        ),
    ]
