# Generated by Django 5.1.3 on 2025-05-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_alter_order_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('student', 'student'), ('doctor', 'doctor')], max_length=10),
        ),
    ]
