# Generated by Django 5.1.3 on 2025-02-28 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_alter_item_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageitem',
            name='photo',
        ),
    ]
