# Generated by Django 5.1.3 on 2025-05-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_alter_category_category_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_points', models.IntegerField(default=0)),
                ('purchase_points', models.IntegerField(default=0)),
                ('referral_purchase_points', models.IntegerField(default=0)),
            ],
        ),
    ]
