# Generated by Django 5.1.3 on 2025-02-28 13:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_packageitem_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageitem',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
