# Generated by Django 5.1.3 on 2025-06-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_order_customer_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
