# Generated by Django 5.1.3 on 2025-02-22 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagament', '0002_profile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referral_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='usermanagament.profile'),
        ),
    ]
