# Generated by Django 5.1.3 on 2025-03-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagament', '0004_alter_profile_referred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referred_by',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
