# Generated by Django 5.1.3 on 2025-06-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagament', '0005_alter_profile_referred_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_password', models.CharField(default=1234, max_length=40)),
                ('sub_admin_password', models.CharField(default=123, max_length=40)),
            ],
        ),
    ]
