# Generated by Django 5.1.3 on 2025-06-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagament', '0006_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_password',
            field=models.CharField(default='1234', max_length=40),
        ),
        migrations.AlterField(
            model_name='admin',
            name='sub_admin_password',
            field=models.CharField(default='123', max_length=40),
        ),
    ]
